# Generated by Django 4.1.6 on 2023-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=20)),
                ('mail', models.EmailField(default='', max_length=30)),
            ],
            options={
                'db_table': 'krishna_register',
            },
        ),
    ]
                