# Generated by Django 4.1.6 on 2023-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=20)),
                ('myfile', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
