# Generated by Django 4.1.6 on 2023-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Push',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
                ('publish', models.BooleanField(max_length=10000)),
            ],
            options={
                'db_table': 'publish',
            },
        ),
    ]
